<?php
// Email Configuration for WMSU Gym Reservation System

// SMTP Configuration (using PHPMailer)
// You can use Gmail, Outlook, or your institution's SMTP server

define('SMTP_HOST', 'smtp.gmail.com'); // Change to your SMTP server
define('SMTP_PORT', 587); // Usually 587 for TLS, 465 for SSL
define('SMTP_USERNAME', 'wmsugymreservationsystem@gmail.com'); // Your email address
define('SMTP_PASSWORD', 'lnccjyzfribnbtmr'); // Your email password or app password
define('SMTP_ENCRYPTION', 'tls'); // 'tls' or 'ssl'
define('FROM_EMAIL', 'wmsugymreservationsystem@gmail.com'); // Sender email
define('FROM_NAME', 'WMSU Gym Reservation System'); // Sender name

// Load Composer autoloader and import PHPMailer classes
require_once __DIR__ . '/vendor/autoload.php'; // Make sure to install PHPMailer via Composer

// Use fully-qualified class names below to avoid static-analysis issues when the
// Composer autoloader is not available to the analyzer.

// Function to send email using PHPMailer
function sendEmail($to_email, $to_name, $subject, $body) {
    $mail = new \PHPMailer\PHPMailer\PHPMailer(true);
    
    try {
        // Server settings
        $mail->isSMTP();
        $mail->Host = SMTP_HOST;
        $mail->SMTPAuth = true;
        $mail->Username = SMTP_USERNAME;
        $mail->Password = SMTP_PASSWORD;
        $mail->SMTPSecure = SMTP_ENCRYPTION;
        $mail->Port = SMTP_PORT;
        
        // Recipients
        $mail->setFrom(FROM_EMAIL, FROM_NAME);
        $mail->addAddress($to_email, $to_name);
        
        // Content
        $mail->isHTML(true);
        $mail->Subject = $subject;
        $mail->Body = $body;
        $mail->AltBody = strip_tags($body);
        
        $mail->send();
        return true;
    } catch (\PHPMailer\PHPMailer\Exception $e) {
        // Use the caught exception variable and also include PHPMailer error info
        error_log("Email Error: {$mail->ErrorInfo}; Exception: " . $e->getMessage());
        return false;
    }
}

// Alternative: Simple PHP mail() function (if PHPMailer is not available)
function sendSimpleEmail($to_email, $subject, $body) {
    $headers = "MIME-Version: 1.0" . "\r\n";
    $headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";
    $headers .= "From: " . FROM_NAME . " <" . FROM_EMAIL . ">" . "\r\n";
    
    return mail($to_email, $subject, $body, $headers);
}

// Email template for account approval
function getAccountApprovalEmailTemplate($name, $email, $password) {
    $login_url = "http://" . $_SERVER['HTTP_HOST'] . "/login.php"; // Adjust as needed
    $year = date('Y');
    
    return "
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset='UTF-8'>
        <style>
            body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
            .container { max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f9f9f9; }
            .header { background-color: #8B0000; color: white; padding: 20px; text-align: center; border-radius: 5px 5px 0 0; }
            .content { background-color: white; padding: 30px; border-radius: 0 0 5px 5px; }
            .credentials { background-color: #f0f0f0; padding: 15px; border-left: 4px solid #8B0000; margin: 20px 0; }
            .button { display: inline-block; background-color: #8B0000; color: white; padding: 12px 30px; text-decoration: none; border-radius: 5px; margin: 20px 0; }
            .warning { background-color: #fff3cd; border-left: 4px solid #ffc107; padding: 15px; margin: 20px 0; }
            .footer { text-align: center; padding: 20px; color: #777; font-size: 12px; }
        </style>
    </head>
    <body>
        <div class='container'>
            <div class='header'>
                <h1>🎉 Account Approved!</h1>
                <p>WMSU Gym Reservation System</p>
            </div>
            
            <div class='content'>
                <h2>Welcome, {$name}!</h2>
                
                <p>Great news! Your account request has been approved by the administrator.</p>
                
                <p>You can now access the WMSU Gym Reservation System and start making reservations for the gymnasium.</p>
                
                <div class='credentials'>
                    <h3 style='margin-top: 0; color: #8B0000;'>🔐 Your Login Credentials</h3>
                    <p><strong>Email:</strong> {$email}</p>
                    <p><strong>Temporary Password:</strong> <code style='background-color: #e0e0e0; padding: 5px 10px; border-radius: 3px; font-size: 16px;'>{$password}</code></p>
                </div>
                
                <div class='warning'>
                    <strong>⚠️ Important Security Notice:</strong>
                    <ul style='margin: 10px 0; padding-left: 20px;'>
                        <li>This is a temporary password generated by the system</li>
                        <li><strong>Please change your password immediately after your first login</strong></li>
                        <li>Never share your password with anyone</li>
                        <li>Keep this email secure and delete it after changing your password</li>
                    </ul>
                </div>
                
                <div style='text-align: center;'>
                    <a href='{$login_url}' class='button'>Login to Your Account</a>
                </div>
                
                <h3>📋 Next Steps:</h3>
                <ol>
                    <li>Click the login button above or visit the login page</li>
                    <li>Enter your email and temporary password</li>
                    <li>Go to your profile settings and change your password</li>
                    <li>Start making gym reservations!</li>
                </ol>
                
                <h3>📞 Need Help?</h3>
                <p>If you have any questions or need assistance, please contact the gymnasium administrator.</p>
            </div>
            
            <div class='footer'>
                <p>© {$year} Western Mindanao State University</p>
                <p>WMSU Gym Reservation System</p>
                <p style='color: #999; font-size: 11px;'>This is an automated message. Please do not reply to this email.</p>
            </div>a
        </div>
    </body>
    </html>
    ";
}
?>